// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qszflpzaiyijwqlcmopv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzemZscHphaXlpandxbGNtb3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzkwMzgsImV4cCI6MjA1OTY1NTAzOH0.HmkiGPoAB2RqFPQPEgUxrts8UOew3QiU1MZNBkd2QjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);